name: Auto Merge

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted

jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      contents: write      # Permissions to modify repository contents
      pull-requests: write # Permissions to manage pull requests

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Debug GH_TOKEN
        run: echo "GH_TOKEN is set"
        env:
          GH_TOKEN: ${{ github.token }}

      # Ensure PR is mergeable, check for reviews, and merge if possible
      - name: Ensure PR is mergeable
        id: mergeable
        env:
          GH_TOKEN: ${{ github.token }}  # Pass GitHub token to GH CLI
        run: |
          pr_details=$(gh pr view ${{ github.event.pull_request.number }} --json mergeable --jq .)
          mergeable=$(echo "$pr_details" | jq -r .mergeable)
          echo "Mergeable state: $mergeable"
          if [ "$mergeable" != "MERGEABLE" ]; then
            echo "Pull request is not mergeable."
            exit 1
          fi

      - name: Automerge PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN  }}  # Use GITHUB_TOKEN here
          script: |
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });

            if (pr.mergeable_state === 'dirty') {
              console.log('Pull request has merge conflicts.');
              return;
            }

            if (pr.mergeable) {
              await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number,
                merge_method: 'squash',
                commit_title: 'Auto-merged by GitHub Actions'
              });
              console.log('Pull request merged.');
            } else {
              console.log('Pull request is not mergeable.');
            }
