name: Auto Merge

on:
  pull_request_target:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked

  pull_request_review:
    types:
      - submitted  # Trigger when a review is submitted (approved or changes requested)

  check_suite:
    types:
      - completed

  status: {}

jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      contents: read       # Read repository content
      pull-requests: write # Write access to PRs (to merge them)
      actions: write       # Allow executing actions

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ensure PR is mergeable
        id: mergeable
        env:
          GH_TOKEN: ${{ github.token }}  # Default GitHub token provided by GitHub Actions
        run: |
          pr_details=$(gh pr view ${{ github.event.pull_request.number }} --json mergeable --jq .)
          echo "PR Details: $pr_details"

          # Fetch the mergeable field
          mergeable=$(echo "$pr_details" | jq -r .mergeable)

          echo "Mergeable state: $mergeable"

          if [ "$mergeable" = "MERGEABLE" ]; then
            echo "Pull request is mergeable."
          elif [ "$mergeable" = "false" ]; then
            echo "Pull request is not mergeable."
            exit 1
          elif [ "$mergeable" = "null" ]; then
            echo "Mergeable state is unknown. Please check the PR status."
            exit 1
          else
            echo "Unexpected mergeable state: $mergeable"
            exit 1
          fi

      - name: Ensure Required Approvals
        id: approvals
        uses: actions/github-script@v6
        with:
          github-token: ${{ github.token }}
          script: |
            const { data: reviews } = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });

            // Debugging: log all review states
            console.log(`Reviews submitted: ${reviews.map(review => review.state).join(", ")}`);
            
            // Filter reviews that have been "APPROVED"
            const approvedReviews = reviews.filter(review => review.state === "APPROVED");
            const requiredApprovals = 1;  // Set this according to your repo's approval rules

            console.log(`Found ${approvedReviews.length} approvals.`);

            if (approvedReviews.length < requiredApprovals) {
              core.setFailed(`PR requires at least ${requiredApprovals} approval(s).`);
            } else {
              console.log(`Required approval(s) granted.`);
            }

      - name: Automerge Script
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });

            if (pr.mergeable_state === "dirty") {
              console.log("Pull request has merge conflicts.");
              return;
            }

            if (pr.mergeable_state === "clean") {
              console.log("PR is clean and ready for merging.");
            } else {
              console.log("Mergeable state:", pr.mergeable_state);
            }

            if (pr.mergeable) {
              await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number,
                merge_method: "squash",
                commit_title: "Auto-merged by GitHub Actions"
              });
            } else {
              console.log("Pull request is not mergeable.");
            }

  wait_for_approval_and_retry_merge:
    runs-on: ubuntu-latest
    needs: automerge
    if: ${{ always() }}  # Ensure this job runs after any change in PR state

    permissions:
      contents: read
      pull-requests: write
      actions: write

    steps:
      - name: Retry Automerge Script
        run: |
          echo "Polling for review approvals..."
          
          # Check the PR for review status (using `gh` to fetch PR details)
          pr_details=$(gh pr view ${{ github.event.pull_request.number }} --json mergeable,reviewState --jq '{mergeable: .mergeable, reviewState: .reviews | map(select(.state == "APPROVED")) | length}')

          mergeable=$(echo "$pr_details" | jq -r .mergeable)
          approvals=$(echo "$pr_details" | jq -r .reviewState)

          echo "Mergeable: $mergeable, Approvals: $approvals"

          if [ "$mergeable" == "true" ] && [ "$approvals" -ge 1 ]; then
            echo "PR is mergeable and has sufficient approvals. Proceeding with merge."
            gh pr merge ${{ github.event.pull_request.number }} --squash --commit-title "Auto-merged by GitHub Actions"
          else
            echo "PR is not ready to merge yet (mergeable: $mergeable, approvals: $approvals). Retrying..."
            sleep 30s  # Wait before retrying
          fi
